[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cometusb"
version = "1.0.0"
description = "Create Linux bootable USB from CLI"
readme = "README.md"
authors = [
    { name="Shahid Rahaman", email="shahidrahman333@gmail.com" }
]
<<<<<<< HEAD
license = {file = "LICENSE.txt"}
=======
license = {file = "LICENSE"}
>>>>>>> origin/main
requires-python = ">=3.8"

dependencies = [
    "requests",
    "tqdm",
    "tabulate"
]

<<<<<<< HEAD
[project.urls]
Homepage = "https://github.com/CometUSB/CometUSB"
Documentation = "https://CometUSB.github.io/CometUSB/"
Changelog = "https://github.com/CometUSB/CometUSB/releases"

=======
>>>>>>> origin/main
[project.scripts]
cometusb = "cometusb.cometusb:main"
